In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2
cv2.__version__

'4.9.0'

02_이미지출력

In [9]:
import cv2

img = cv2.imread('cat-640.jpg')
cv2.imshow('cat', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import cv2
img_color = cv2.imread('cat-640.jpg', cv2.IMREAD_COLOR)
img_gray = cv2.imread('cat-640.jpg', cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread('cat-640.jpg', cv2.IMREAD_UNCHANGED)

cv2.imshow('img_color', img_color)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_unchanged', img_unchanged)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
#png로 작업하기
import cv2
img_color = cv2.imread('cat_png.png', cv2.IMREAD_COLOR)
img_gray = cv2.imread('cat_png.png', cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread('cat_png.png', cv2.IMREAD_UNCHANGED)

cv2.imshow('img_color', img_color)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_unchanged', img_unchanged)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
import cv2
img = cv2.imread('cat-640.jpg')
img.shape

(391, 640, 3)

02. 동영상 출력

In [9]:
import cv2
cap = cv2.VideoCapture('cat.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print('더 이상 가져올 프레임이 없어요')
        break

    cv2.imshow('cat_video', frame)
    
    if cv2.waitKey(1) == ord('q'):
        print('사용자 입력에 의해 종료합니다')
        break

cap.release()
cv2.destroyAllWindows()

더 이상 가져올 프레임이 없어요


In [15]:
import cv2
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    exit()

while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imshow('camera', frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

03. 도형그리기

In [23]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

img[:] = (0,255,0)
print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]


In [27]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)
img[100:200, 200:300] = (255,255,255)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

color = (0,255,255)
thickness = 3

cv2.line(img, (50,100), (400,50), color, thickness, cv2.LINE_8)
cv2.line(img, (50,200), (400,150), color, thickness, cv2.LINE_4)
cv2.line(img, (50,300), (400,250), color, thickness, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

color = (255,255,0)
radius = 50
thickness = 10

cv2.circle(img, (200,100), radius, color, thickness, cv2.LINE_AA)
cv2.circle(img, (400,100), radius, color, cv2.FILLED, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

color = (0,255,0)
thickness = 3

cv2.rectangle(img, (100,100), (200,200), color, thickness)
cv2.rectangle(img, (300,100), (400,300), color, cv2.FILLED)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
import cv2
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

color = (0,0,255)
thickness = 3

pts1= np.array([[100,100], [200,100], [100,200]])
pts2= np.array([[200,100], [300,100], [300,200]])

cv2.polylines(img, [pts1, pts2], True, color, thickness, cv2.LINE_AA)

pts3= np.array([[[100,300], [200,300], [100,400]],[[200,300],[300,300],[300,400]]])
cv2.fillPoly(img, pts3, color, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

04. 텍스트

In [39]:
import numpy as np
import cv2

img = np.zeros((480, 640, 3), dtype=np.uint8)

scale = 1
color = (255,255,255)
thickness = 1

cv2.putText(img, 'Nado simplex', (20,50), cv2.FONT_HERSHEY_SIMPLEX, scale, color, thickness)
cv2.putText(img, 'Nado plain', (20,150), cv2.FONT_HERSHEY_PLAIN, scale, color, thickness)
cv2.putText(img, 'Nado script simplex', (20,250), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, scale, color, thickness)
cv2.putText(img, 'Nado Triplex', (20,350), cv2.FONT_HERSHEY_TRIPLEX, scale, color, thickness)
cv2.putText(img, 'Nado Italic', (20,450), cv2.FONT_HERSHEY_TRIPLEX | cv2.FONT_ITALIC, scale, color, thickness)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
#한글 쓸때 

import numpy as np
import cv2

img = np.zeros((480, 640, 3), dtype=np.uint8)

SCALE = 1 # 크기
COLOR = (255, 255, 255) # 흰색
THICKNESS = 1 # 두께

cv2.putText(img, "나도코딩", (20, 50), cv2.FONT_HERSHEY_SIMPLEX, SCALE, COLOR, THICKNESS)
# 그릴 위치, 텍스트 내용, 시작 위치, 폰트 종류, 크기, 색깔, 두께

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
import numpy as np
import cv2
# PIL (Python Image Library)

from PIL import ImageFont, ImageDraw, Image

def myPutText(src, text, pos, font_size, font_color):
    img_pil = Image.fromarray(src)
    draw = ImageDraw.Draw(img_pil)
    font = ImageFont.truetype('fonts/gulim.ttc', font_size)
    draw.text(pos, text, font=font, fill=font_color)
    return np.array(img_pil)

img = np.zeros((480, 640, 3), dtype=np.uint8)

FONT_SIZE = 30
COLOR = (255, 255, 255) # 흰색

# cv2.putText(img, "나도코딩", (20, 50), cv2.FONT_HERSHEY_SIMPLEX, SCALE, COLOR, THICKNESS)
# 그릴 위치, 텍스트 내용, 시작 위치, 폰트 종류, 크기, 색깔, 두께
img = myPutText(img, "나도코딩", (20, 50), FONT_SIZE, COLOR)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'PIL'